// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int nonNegative = Integer.parseInt(args[0]);
		int bigger = 0; 
		int smallerOrEqual= 0 ;
		for (int i = 0; i < nonNegative; i ++) { //הלולאה רצה n פעמים
			double random = Math.random() ;
			if (random > 0.5){
				bigger++;
			} else {
			smallerOrEqual++;
			}
		}
	System.out.println("> 0.5: " + bigger + " times");
	System.out.println("<= 0.5: " +smallerOrEqual+ " times");
	if (bigger != 0 && smallerOrEqual != 0) {
        System.out.println("Ratio: " + ((double) bigger / smallerOrEqual));
        }
	}
}
